version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data_brut:/data_brut
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - superset-network

  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_WEBSERVER_PORT: 8088
      SUPERSET_ADMIN_USER: admin
      SUPERSET_ADMIN_PASSWORD: admin
      SUPERSET_DB_URI: postgresql+psycopg2://superset:superset@postgres:5432/superset
      SUPERSET_SECRET_KEY: "your_secret_key_here"
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    volumes:
      - superset_home:/app/superset_home
      - ./superset_config.py:/stackdemo/superset_config.py
      - ./init_superset.sh:/app/docker-entrypoint.sh
    entrypoint: /app/docker-entrypoint.sh
    networks:
      - superset-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - superset-network

networks:
  superset-network:

volumes:
  pgdata:
  superset_home:
  pgadmin_data: